#!/bin/sh                                                                       
# 
# start sustom settings
#

start() {
  echo "modprobe wlan"
#  modprobe mt7601u
#  modprobe esp8089
#  /bin/sleep 2

  timeout=0; 
  while ! ip a | grep -q 'wlan' ; do 
    if [ $timeout -ge 10 ] ; then break; fi;
    timeout=$((timeout+1));
    sleep 1; 
  done;
  echo "wlan timeout $timeout"

}
stop() {
        echo "stop esp8089"
#        rmmod esp8089
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
